//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemturaSP.CustomWebParts.AnderolFindProduct {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class AnderolFindProduct {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Repeater rprProduct;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(AnderolFindProduct target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control3() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(3, 2);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                <div class=\"result\">\r\n                    \r\n                   " +
                    " <a href=\'/sites/anderol/Pages/Product_Details.aspx?Prod=");
            @__ctrl.SetStaticString(1, "\'>\r\n                        <h4>");
            @__ctrl.SetStaticString(2, "</h4>\r\n                    </a>\r\n                </div>\r\n\r\n\r\n               \r\n   " +
                    "         ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control3);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        public void @__DataBind__control3(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("Title"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(1, global::System.Convert.ToString(Eval("ProdName"), global::System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlrprProduct() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            this.rprProduct = @__ctrl;
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "rprProduct";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::ChemturaSP.CustomWebParts.AnderolFindProduct.AnderolFindProduct @__ctrl) {
            global::System.Web.UI.WebControls.Repeater @__ctrl1;
            @__ctrl1 = this.@__BuildControlrprProduct();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<script type=\"text/javascript\" src=\"/sites/anderol/Style Library/AnderolCusto" +
                    "mFiles/Scripts/jquery-1.7.2.min.js\"></script>\r\n\r\n\r\n\r\n<script type=\"text/javascri" +
                    "pt\" src=\"/sites/anderol/Style Library/AnderolCustomFiles/Scripts/jquery.selectbo" +
                    "x-0.1.3.js\"></script>\r\n\r\n\r\n\r\n<link href=\"/sites/anderol/Style Library/AnderolCus" +
                    "tomFiles/Styles/AnderolProducts.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n\r\n\r\n<d" +
                    "iv id=\"productSelectorWrapper\">\r\n    <div class=\"productSelector\">\r\n        <h3>" +
                    "FIND THE RIGHT PRODUCT</h3>\r\n        <!--<input id=\"searchText\" type=\"text\" oncl" +
                    "ick=\"if(this.value==\'Search\'){this.value = \'\';}\" value=\"Search\" />-->\r\n        <" +
                    "input id=\"searchText\" onfocus=\"if (this.value==\'Search\') this.value = \'\'\" onblur" +
                    "=\"if (this.value==\'\') this.value = \'Search\'\" type=\"text\" maxlength=\"80\" value=\"S" +
                    "earch\" />\r\n        <h4>Aerospace and Defense</h4>\r\n        \r\n        <select cla" +
                    "ss=\"pfSelect\" id=\"ddlAerospace\" name=\"Aerospace--and--Defense\">\r\n            <op" +
                    "tion value=\"\"></option>\r\n            <option value=\"/Aerospace--and--Defense/Hyd" +
                    "raulic--Fluids/\">Hydraulic Fluids</option>\r\n            <option value=\"/Aerospac" +
                    "e--and--Defense/Performance--Compounds--and--Greases/\">Performance Compounds and" +
                    " Greases</option>\r\n            <option value=\"/Aerospace--and--Defense/Specialty" +
                    "--Application--and--Performance--Fluids/\">Specialty Application and Performance " +
                    "Fluids</option>\r\n            <option value=\"/Aerospace--and--Defense/Turbine--an" +
                    "d--Drivetrain--Fluids/\">Turbine and Drivetrain Fluids</option>\r\n            <opt" +
                    "ion value=\"/Aerospace--and--Defense/Weapons--Cleaner--and--Preservative--Lubes/\"" +
                    ">Weapons Cleaner and Preservative Lubes</option>\r\n        </select>\r\n        <h4" +
                    ">Industrial</h4>\r\n        \r\n        <select class=\"pfSelect\" id=\"ddlIndustrial\" " +
                    "name=\"Industrial\">\r\n            <option value=\"\"></option>\r\n            <option " +
                    "value=\"/Industrial/Compressors--and--Vacuum--Pumps/\">Compressors and Vacuum Pump" +
                    "s</option>\r\n            <option value=\"/Industrial/Food--Machinery/\">Food Machin" +
                    "ery</option>\r\n            <option value=\"/Industrial/Gas--Turbine--Lubricants/\">" +
                    "Gas Turbine Lubricants</option>\r\n            <option value=\"/Industrial/Gears--a" +
                    "nd--Bearings/\">Gears and Bearings</option>\r\n            <option value=\"/Industri" +
                    "al/Greases/\">Greases</option>\r\n            <option value=\"/Industrial/Hydraulics" +
                    "/\">Hydraulics</option>\r\n            <option value=\"/Industrial/Refrigeration/\">R" +
                    "efrigeration</option>\r\n        </select>\r\n        <input type=\"button\" id=\"reset" +
                    "\" name=\"reset\" onclick=\"resetProductsearch()\" value=\"Reset\" title=\"Reset\" />\r\n  " +
                    "  </div>\r\n    <div class=\"selectorResults\" style=\"display: none\">\r\n        <h3>R" +
                    "esults</h3>\r\n        <p class=\'pagination\'></p>\r\n        <div class=\"resultItems" +
                    "\">\r\n        </div>\r\n    </div>\r\n    <!--- /.selectorResults --->\r\n    <div class" +
                    "=\"allProducts\">\r\n        <h3>All Products</h3>\r\n        ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write(@"
    </div>

</div>

<script type=""text/javascript"">
    $(document).ready(function () {
        //set drop down on change functions



        //$('#ddlAerospace').change(function () {
        $('[id*=ddlAerospace]').change(function (e) {

            dropDownChanged();

            //Set to display results on first page
            currentpage = 1;

            //displayProducts();
            setProducts();
        });

        // $('#ddlIndustrial').change(function () {
        $('[id*=ddlIndustrial]').change(function (e) {
            // alert(""Hi"");
            dropDownChanged();

            //Set to display results on first page
            currentpage = 1;

            //displayProducts();
            setProducts();
        });

        //Trigger search is return key pressed inside search box
        $(""#searchText"").keyup(function (event) {
            //if(event.keyCode == 13)
            //{
            //displayProducts();
            setProducts();
            //}
        });

    });

    // start user setings
    var maxColumn = 2;    // max cells in a row
    var range = 3;    // range of num links to show
    // end user setings

    var rowsPerPage = 10;
    var currentpage = 1;
    var sortBy = '';
    var sortOrder = 0;
    var searchText = '';
    var resultsMsg = '';

    var selectedCategories = new Array();
    var products = [");
            @__w.Write(strProdJSON);

            @__w.Write("];\r\n    var categories = [");
              @__w.Write(strCatJSON);

            @__w.Write("];\r\n    // var categories = [\'Home/Markets--and--Applications/Aerospace--and--Def" +
                    "ense/Hydraulic--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defe" +
                    "nse/Hydraulic--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defen" +
                    "se/Hydraulic--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defens" +
                    "e/Hydraulic--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense" +
                    "/Hydraulic--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/" +
                    "Hydraulic--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/H" +
                    "ydraulic--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Hy" +
                    "draulic--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Per" +
                    "formance--Compounds--and--Greases//\', \'Home/Markets--and--Applications/Aerospace" +
                    "--and--Defense/Performance--Compounds--and--Greases//\', \'Home/Markets--and--Appl" +
                    "ications/Aerospace--and--Defense/Performance--Compounds--and--Greases//\', \'Home/" +
                    "Markets--and--Applications/Aerospace--and--Defense/Performance--Compounds--and--" +
                    "Greases//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Performance" +
                    "--Compounds--and--Greases//\', \'Home/Markets--and--Applications/Aerospace--and--D" +
                    "efense/Performance--Compounds--and--Greases//\', \'Home/Markets--and--Applications" +
                    "/Aerospace--and--Defense/Performance--Compounds--and--Greases//\', \'Home/Markets-" +
                    "-and--Applications/Aerospace--and--Defense/Performance--Compounds--and--Greases/" +
                    "/\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Performance--Compou" +
                    "nds--and--Greases//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/P" +
                    "erformance--Compounds--and--Greases//\', \'Home/Markets--and--Applications/Aerospa" +
                    "ce--and--Defense/Performance--Compounds--and--Greases//\', \'Home/Markets--and--Ap" +
                    "plications/Aerospace--and--Defense/Specialty--Application--and--Performance--Flu" +
                    "ids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Specialty--Appl" +
                    "ication--and--Performance--Fluids//\', \'Home/Markets--and--Applications/Aerospace" +
                    "--and--Defense/Specialty--Application--and--Performance--Fluids//\', \'Home/Market" +
                    "s--and--Applications/Aerospace--and--Defense/Specialty--Application--and--Perfor" +
                    "mance--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Speci" +
                    "alty--Application--and--Performance--Fluids//\', \'Home/Markets--and--Applications" +
                    "/Aerospace--and--Defense/Specialty--Application--and--Performance--Fluids//\', \'H" +
                    "ome/Markets--and--Applications/Aerospace--and--Defense/Specialty--Application--a" +
                    "nd--Performance--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Def" +
                    "ense/Specialty--Application--and--Performance--Fluids//\', \'Home/Markets--and--Ap" +
                    "plications/Aerospace--and--Defense/Specialty--Application--and--Performance--Flu" +
                    "ids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Specialty--Appl" +
                    "ication--and--Performance--Fluids//\', \'Home/Markets--and--Applications/Aerospace" +
                    "--and--Defense/Specialty--Application--and--Performance--Fluids//\', \'Home/Market" +
                    "s--and--Applications/Aerospace--and--Defense/Specialty--Application--and--Perfor" +
                    "mance--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Turbi" +
                    "ne--and--Drivetrain--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and-" +
                    "-Defense/Turbine--and--Drivetrain--Fluids//\', \'Home/Markets--and--Applications/A" +
                    "erospace--and--Defense/Turbine--and--Drivetrain--Fluids//\', \'Home/Markets--and--" +
                    "Applications/Aerospace--and--Defense/Turbine--and--Drivetrain--Fluids//\', \'Home/" +
                    "Markets--and--Applications/Aerospace--and--Defense/Turbine--and--Drivetrain--Flu" +
                    "ids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/Turbine--and--D" +
                    "rivetrain--Fluids//\', \'Home/Markets--and--Applications/Aerospace--and--Defense/W" +
                    "eapons--Cleaner--and--Preservative--Lubes//\', \'Home/Markets--and--Applications/A" +
                    "erospace--and--Defense/Weapons--Cleaner--and--Preservative--Lubes//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Compressors--and--Vacuum--Pumps//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Food--Machinery//\', \'Home/Markets--and--Applic" +
                    "ations/Industrial/Food--Machinery//\', \'Home/Markets--and--Applications/Industria" +
                    "l/Food--Machinery//\', \'Home/Markets--and--Applications/Industrial/Food--Machiner" +
                    "y//\', \'Home/Markets--and--Applications/Industrial/Food--Machinery//\', \'Home/Mark" +
                    "ets--and--Applications/Industrial/Food--Machinery//\', \'Home/Markets--and--Applic" +
                    "ations/Industrial/Food--Machinery//\', \'Home/Markets--and--Applications/Industria" +
                    "l/Food--Machinery//\', \'Home/Markets--and--Applications/Industrial/Food--Machiner" +
                    "y//\', \'Home/Markets--and--Applications/Industrial/Gas--Turbine--Lubricants//\', \'" +
                    "Home/Markets--and--Applications/Industrial/Gas--Turbine--Lubricants//\', \'Home/Ma" +
                    "rkets--and--Applications/Industrial/Gas--Turbine--Lubricants//\', \'Home/Markets--" +
                    "and--Applications/Industrial/Gas--Turbine--Lubricants//\', \'Home/Markets--and--Ap" +
                    "plications/Industrial/Gas--Turbine--Lubricants//\', \'Home/Markets--and--Applicati" +
                    "ons/Industrial/Gas--Turbine--Lubricants//\', \'Home/Markets--and--Applications/Ind" +
                    "ustrial/Gas--Turbine--Lubricants//\', \'Home/Markets--and--Applications/Industrial" +
                    "/Gears--and--Bearings//\', \'Home/Markets--and--Applications/Industrial/Gears--and" +
                    "--Bearings//\', \'Home/Markets--and--Applications/Industrial/Gears--and--Bearings/" +
                    "/\', \'Home/Markets--and--Applications/Industrial/Gears--and--Bearings//\', \'Home/M" +
                    "arkets--and--Applications/Industrial/Gears--and--Bearings//\', \'Home/Markets--and" +
                    "--Applications/Industrial/Gears--and--Bearings//\', \'Home/Markets--and--Applicati" +
                    "ons/Industrial/Gears--and--Bearings//\', \'Home/Markets--and--Applications/Industr" +
                    "ial/Gears--and--Bearings//\', \'Home/Markets--and--Applications/Industrial/Gears--" +
                    "and--Bearings//\', \'Home/Markets--and--Applications/Industrial/Gears--and--Bearin" +
                    "gs//\', \'Home/Markets--and--Applications/Industrial/Gears--and--Bearings//\', \'Hom" +
                    "e/Markets--and--Applications/Industrial/Gears--and--Bearings//\', \'Home/Markets--" +
                    "and--Applications/Industrial/Gears--and--Bearings//\', \'Home/Markets--and--Applic" +
                    "ations/Industrial/Gears--and--Bearings//\', \'Home/Markets--and--Applications/Indu" +
                    "strial/Gears--and--Bearings//\', \'Home/Markets--and--Applications/Industrial/Gear" +
                    "s--and--Bearings//\', \'Home/Markets--and--Applications/Industrial/Gears--and--Bea" +
                    "rings//\', \'Home/Markets--and--Applications/Industrial/Gears--and--Bearings//\', \'" +
                    "Home/Markets--and--Applications/Industrial/Gears--and--Bearings//\', \'Home/Market" +
                    "s--and--Applications/Industrial/Gears--and--Bearings//\', \'Home/Markets--and--App" +
                    "lications/Industrial/Greases//\', \'Home/Markets--and--Applications/Industrial/Gre" +
                    "ases//\', \'Home/Markets--and--Applications/Industrial/Greases//\', \'Home/Markets--" +
                    "and--Applications/Industrial/Greases//\', \'Home/Markets--and--Applications/Indust" +
                    "rial/Greases//\', \'Home/Markets--and--Applications/Industrial/Greases//\', \'Home/M" +
                    "arkets--and--Applications/Industrial/Greases//\', \'Home/Markets--and--Application" +
                    "s/Industrial/Greases//\', \'Home/Markets--and--Applications/Industrial/Greases//\'," +
                    " \'Home/Markets--and--Applications/Industrial/Greases//\', \'Home/Markets--and--App" +
                    "lications/Industrial/Greases//\', \'Home/Markets--and--Applications/Industrial/Gre" +
                    "ases//\', \'Home/Markets--and--Applications/Industrial/Greases//\', \'Home/Markets--" +
                    "and--Applications/Industrial/Greases//\', \'Home/Markets--and--Applications/Indust" +
                    "rial/Greases//\', \'Home/Markets--and--Applications/Industrial/Greases//\', \'Home/M" +
                    "arkets--and--Applications/Industrial/Greases//\', \'Home/Markets--and--Application" +
                    "s/Industrial/Greases//\', \'Home/Markets--and--Applications/Industrial/Greases//\'," +
                    " \'Home/Markets--and--Applications/Industrial/Hydraulics//\', \'Home/Markets--and--" +
                    "Applications/Industrial/Hydraulics//\', \'Home/Markets--and--Applications/Industri" +
                    "al/Hydraulics//\', \'Home/Markets--and--Applications/Industrial/Hydraulics//\', \'Ho" +
                    "me/Markets--and--Applications/Industrial/Hydraulics//\', \'Home/Markets--and--Appl" +
                    "ications/Industrial/Hydraulics//\', \'Home/Markets--and--Applications/Industrial/H" +
                    "ydraulics//\', \'Home/Markets--and--Applications/Industrial/Hydraulics//\', \'Home/M" +
                    "arkets--and--Applications/Industrial/Refrigeration//\', \'Home/Markets--and--Appli" +
                    "cations/Industrial/Refrigeration//\', \'Home/Markets--and--Applications/Industrial" +
                    "/Refrigeration//\', \'Home/Markets--and--Applications/Industrial/Refrigeration//\'," +
                    " \'Home/Markets--and--Applications/Industrial/Refrigeration//\', \'Home/Markets--an" +
                    "d--Applications/Industrial/Refrigeration//\'];\r\n\r\n    function resetProductsearch" +
                    "() {\r\n        searchText = \"\";\r\n        selectedCategories = [];\r\n\r\n        $(\"#" +
                    "searchText\").val(\"Search\");\r\n        $(\".pfSelect\").each(function () {\r\n        " +
                    "    $(this).val(\"\");\r\n            if ($(this).attr(\"id\").indexOf(\"_\") > 0) {\r\n\r\n" +
                    "                $(\'[id*=ddlAerospace]\').prop(\'selectedIndex\', 0);\r\n             " +
                    "   $(\'[id*=ddlIndustrial]\').prop(\'selectedIndex\', 0);\r\n\r\n                //this " +
                    "is a child dro down - hide\r\n                // $(this).hide();\r\n            }\r\n " +
                    "       });\r\n        $(\'.resultItems\').html(\"\");\r\n        $(\'.selectorResults\').h" +
                    "ide();\r\n        $(\'.allProducts\').show();\r\n    }\r\n\r\n    function setProducts() {" +
                    "\r\n        searchText = $(\"input#searchText\").val();\r\n        // alert(searchText" +
                    ");\r\n        var countCellData = 0;\r\n        var offset = 0;\r\n        // empty co" +
                    "ntent\r\n\r\n        var filterdProducts = [];  // displayed products array\r\n       " +
                    " var key = 0;\r\n\r\n        resultsMsg = \"<h2>No results matched your search</h2>\";" +
                    "\r\n\r\n        if (searchText == null || searchText == \"Search\") {\r\n            sea" +
                    "rchText = \"\";\r\n        }\r\n\r\n        if (selectedCategories.length > 0 || searchT" +
                    "ext != \"\") {\r\n            //There are selected categories to search on\r\n        " +
                    "    $.each(products, function (i, object) {\r\n                var productOK = fal" +
                    "se;\r\n                var productFail = false;\r\n\r\n                if (searchText " +
                    "!= \'\') {\r\n                    searchText = searchText.toUpperCase();\r\n          " +
                    "          //remove special characters from search string\r\n                    se" +
                    "archText = searchText.replace(\"&copy;\", \"\");\r\n                    searchText = s" +
                    "earchText.replace(\"™\", \"\");\r\n                    searchText = searchText.replace" +
                    "(\"°\", \"\");\r\n\r\n                    var fieldsToSearch = object.title + object.sho" +
                    "rtDesc + \" force object to text\";\r\n                    fieldsToSearch = fieldsTo" +
                    "Search.toUpperCase();\r\n\r\n                    if (searchText.indexOf(\" \") > 0) {\r" +
                    "\n                        //search text contains multiple words\r\n\r\n              " +
                    "          //split the search text into an array of individual words\r\n           " +
                    "             var searchWords = searchText.split(\" \");\r\n\r\n                       " +
                    " for (var ind = 0; ind < searchWords.length; ind++) {\r\n                         " +
                    "   var searchWord = searchWords[ind];\r\n                            if (searchWor" +
                    "d.length > 0) {\r\n                                if (fieldsToSearch.indexOf(sear" +
                    "chWord, 0) > -1) {\r\n                                    productOK = true;\r\n     " +
                    "                           }\r\n                                else {\r\n          " +
                    "                          productFail = true;\r\n                                }" +
                    "\r\n                            }\r\n                        }\r\n                    " +
                    "}\r\n                    else {\r\n                        //search text contains a " +
                    "single word\r\n                        if (fieldsToSearch.indexOf(searchText, 0) >" +
                    " -1) {\r\n                            productOK = true;\r\n                        }" +
                    "\r\n                        else {\r\n                            productFail = true" +
                    ";\r\n                        }\r\n                    }\r\n\r\n                }\r\n\r\n    " +
                    "            //Simple search for drop down search within drop down option\r\n      " +
                    "          var productCategory = object.categories + \'force object to text\';\r\n   " +
                    "             //loop through all selected categories. Select this product if all " +
                    "categories match\r\n                for (var i = 0; i < selectedCategories.length;" +
                    " i++) {\r\n\r\n                    if (productCategory.indexOf(selectedCategories[i]" +
                    ", 0) > -1) {\r\n                        //This product references the category str" +
                    "ing selected by the drop downs\r\n                        productOK = true;\r\n     " +
                    "               }\r\n                    else {\r\n                        productFai" +
                    "l = true;\r\n                    }\r\n                };\r\n\r\n                //add th" +
                    "is product to the filteredProduct list if it matches all selected drop downs and" +
                    " search text\r\n                if (productOK && !productFail) {\r\n                " +
                    "    filterdProducts[key] = object;\r\n                    key++;\r\n                " +
                    "}\r\n\r\n            });\r\n\r\n            // get the amount of results\r\n            va" +
                    "r totalResults = filterdProducts.length;\r\n\r\n            /****** start build pagi" +
                    "nation links ******/\r\n            var totalpages = Math.ceil(totalResults / rows" +
                    "PerPage); // calculate the total pages\r\n\r\n            if (totalpages > 1) {\r\n   " +
                    "             // fix displayed page number if its biger then exist\r\n             " +
                    "   if (currentpage > totalpages) {\r\n                    // set current page to l" +
                    "ast page\r\n                    currentpage = totalpages;\r\n                }\r\n    " +
                    "            // set the offset of the list, based on current page\r\n              " +
                    "  offset = (currentpage - 1) * rowsPerPage;\r\n\r\n                var pagination = " +
                    "\'\';\r\n                var lastPage = 0;\r\n                // set the min page of t" +
                    "he list, based on the range\r\n                var minPage = parseFloat(currentpag" +
                    "e) - parseFloat(range);\r\n                minPage = minPage > 0 ? minPage : 1;\r\n " +
                    "               // if not page 1, don\'t show back links\r\n                if (curr" +
                    "entpage > 1) {\r\n                    // get previous page num\r\n                  " +
                    "  pagination += \'<button type=\"button\" name=\"\' + (currentpage - 1) + \'\" class=\"p" +
                    "roduct_button\" title=\"&#9668;Previous\" >&#9668;Previous<\\/button>\';\r\n           " +
                    "         // show page 1 only if the min page isn`t page 1 (prevent page 1 to sho" +
                    "w twice)\r\n                    if (minPage > 1) {\r\n                        pagina" +
                    "tion += \'<button type=\"button\" name=\"1\" class=\"product_button\" title=\"1\" >1<\\/bu" +
                    "tton>\';\r\n                    }\r\n                }\r\n\r\n                // loop to " +
                    "show links to range of pages around current page\r\n                for (var x = m" +
                    "inPage; x <= (currentpage + range) ; x++) {\r\n                    // validate pag" +
                    "e number\r\n                    if (x <= totalpages) {\r\n                        la" +
                    "stPage = x;\r\n                        // if this is current page set its value to" +
                    " 0 (prevent click) and set class as selected\r\n                        if (x == c" +
                    "urrentpage) {\r\n                            pagination += \'<button type=\"button\" " +
                    "name=\"0\" class=\"product_button_selected\" title=\"\' + x + \'\" >\' + x + \'<\\/button>\'" +
                    ";\r\n                        } else {\r\n                            pagination += \'" +
                    "<button type=\"button\" name=\"\' + x + \'\" class=\"product_button\" title=\"\' + x + \'\" " +
                    ">\' + x + \'<\\/button>\';\r\n                        }\r\n                    }\r\n      " +
                    "          }\r\n\r\n                // if not on last page, show forward and last pag" +
                    "e links\r\n                if (currentpage != totalpages) {\r\n                    /" +
                    "/ get next page\r\n                    var nextPage = parseFloat(currentpage) + 1;" +
                    "\r\n                    if (lastPage < totalpages) {\r\n                        // s" +
                    "how page last page only if the min page isn`t last page (prevent page 1 to show " +
                    "twice)\r\n                        pagination += \'<button type=\"button\" name=\"\' + t" +
                    "otalpages + \'\" class=\"product_button\" title=\"\' + totalpages + \'\" >\' + totalpages" +
                    " + \'<\\/button>\';\r\n                    }\r\n                    pagination += \'<but" +
                    "ton type=\"button\" name=\"\' + nextPage + \'\" class=\"product_button\" title=\"Next&#96" +
                    "58;\" >Next&#9658;<\\/button>\';\r\n                }\r\n                // update the " +
                    "html\r\n                $(\'.pagination\').html(pagination);\r\n            } else {\r\n" +
                    "                // if no pages or just one page dont show pagination\r\n          " +
                    "      $(\'.pagination\').html(\'<button type=\"button\" name=\"0\" class=\"product_butto" +
                    "n_selected\" title=\"1\" >1<\\/button>\');\r\n            }\r\n            var offsetEnd " +
                    "= parseFloat(rowsPerPage) + parseFloat(offset);\r\n            /****** end build p" +
                    "agination links ******/\r\n\r\n\r\n            // build cells content\r\n            var" +
                    " cell = \"\";\r\n\r\n            var pageProducts = filterdProducts.slice(offset, offs" +
                    "etEnd);\r\n            $.each(pageProducts, function (i, object) {\r\n              " +
                    "  countCellData++; // flug to know if there is content\r\n                cell += " +
                    "\"<div class=\'result\'>\\n\";\r\n                cell += \"   <h4><a href=\'\" + object.l" +
                    "ink + \"\'>\" + object.title + \"</a></h4>\\n\";\r\n                cell += \"   <p>\" + o" +
                    "bject.shortDesc + \"</p>\";\r\n                cell += \"</div>\\n\";\r\n\r\n            })" +
                    ";\r\n\r\n            if (countCellData > 0) {\r\n                // if exist content\r\n" +
                    "                $(\'.resultItems\').html(cell);\r\n            }\r\n            else {" +
                    "\r\n                cell = resultsMsg + cell;\r\n                $(\'.resultItems\').h" +
                    "tml(cell);\r\n            }\r\n\r\n            $(\'.allProducts\').hide();\r\n            " +
                    "$(\'.selectorResults\').show();\r\n\r\n        }\r\n        else {\r\n            //No sea" +
                    "rch criteria - display all products\r\n            $(\'.resultItems\').html(\"\");\r\n  " +
                    "          $(\'.selectorResults\').hide();\r\n            $(\'.allProducts\').show();\r\n" +
                    "        }\r\n\r\n        setPagination();\r\n    }\r\n\r\n\r\n    // animante list display\r\n" +
                    "    /*\r\n    function displayProducts()\r\n    {\r\n        $(\'.selectorResults\').fad" +
                    "eOut(\'slow\', function() {\r\n            // Animation complete\r\n            setPro" +
                    "ducts();\r\n            $(\'.selectorResults\').fadeIn(\'slow\');\r\n        });\r\n    }\r" +
                    "\n    */\r\n\r\n    function dropDownChanged() {\r\n\r\n        //A drop down has been ch" +
                    "anged. Loop through all drop downs and set the selectedCategories Array\r\n       " +
                    " //add selected category to the selectedCategories Array\r\n        selectedCatego" +
                    "ries = [];\r\n        $(\".pfSelect\").each(function () {\r\n            var dropDownI" +
                    "ndex = this.selectedIndex;\r\n            var dropDownValues = this.options;\r\n    " +
                    "        var dropDownValue = dropDownValues[dropDownIndex].value;\r\n            if" +
                    " (dropDownValue != \"\") {\r\n                selectedCategories.push(dropDownValue)" +
                    ";\r\n            }\r\n        });\r\n    }\r\n\r\n\r\n    function setChildDropDown(childNam" +
                    "e, parentName) {\r\n        //Set the values in a child drop down to reflect the v" +
                    "alue selected in the parent\r\n        //show the child drop down if it is not alr" +
                    "eady hidden\r\n\r\n        var parentDropDown = document.getElementById(parentName);" +
                    "\r\n        var parentDropDownIndex = parentDropDown.selectedIndex;\r\n        var p" +
                    "arentDropDownValues = parentDropDown.options;\r\n        var parentDropDownValue =" +
                    " parentDropDownValues[parentDropDownIndex].value;\r\n        var childLastChar = c" +
                    "hildName.substring(childName.length - 1, childName.length);\r\n\r\n        //Set con" +
                    "tents of the child drop down\r\n        $(\'#\' + childName + \' option:gt(0)\').remov" +
                    "e(); // remove all options, but not the first\r\n\r\n        if (parentDropDownValue" +
                    " == \"\") {\r\n            //reset and hide all children\r\n            if (childLastC" +
                    "har == \"1\") {\r\n                //Parent is a top level drop down: Hide all L1 an" +
                    "d any L2 children\r\n                $(\'#\' + parentName + \"_1\").hide();\r\n         " +
                    "       $(\'#\' + parentName + \"_2\").hide();\r\n                $(\'#\' + parentName + " +
                    "\"_2\" + \' option:gt(0)\').remove(); // remove all options, but not the first\r\n    " +
                    "        }\r\n            else if (childLastChar == \"2\") {\r\n                //Paren" +
                    "t is a L1 drop down: Hide L2 child\r\n                $(\'#\' + childName).hide();\r\n" +
                    "            }\r\n        }\r\n        else {\r\n            var allOptions = \"\";\r\n    " +
                    "        $.each(categories, function (i, category) {\r\n                //looping t" +
                    "hrough all cateogories. Include any child cats that include the selected parent " +
                    "value\r\n\r\n                if (category.indexOf(parentDropDownValue, 0) > -1) {\r\n " +
                    "                   //Get child data\r\n                    var catSplit = category" +
                    ".split(\"/\");\r\n                    if (childLastChar == \"1\") {\r\n                 " +
                    "       /*if(catSplit.length > 6)\r\n                        {\r\n                   " +
                    "         //we are dealing with a L3 drop down\r\n                            var c" +
                    "atVal = \"/\" + catSplit[2] + \"/\" + catSplit[3] + \"/\" + catSplit[4];\r\n            " +
                    "                var catText = catSplit[4];\r\n                            if(allOp" +
                    "tions.indexOf(\'<option value=\"\' + catVal + \'\"\') < 0)\r\n                          " +
                    "  {\r\n                                allOptions += \'<option value=\"\' + catVal + " +
                    "\'\">\' + catText + \'</option>\';\r\n                            }\r\n                  " +
                    "      }\r\n                        else */\r\n                        if (catSplit.l" +
                    "ength > 5) {\r\n                            //we are dealing with a L2 drop down\r\n" +
                    "                            var catVal = \"/\" + catSplit[2] + \"/\" + catSplit[3] +" +
                    " \"/\" + catSplit[4];\r\n                            var catText = catSplit[4];\r\n   " +
                    "                         catText = catText.replace(\"--\", \" \");\r\n                " +
                    "            if (allOptions.indexOf(\'<option value=\"\' + catVal + \'\"\') < 0) {\r\n   " +
                    "                             allOptions += \'<option value=\"\' + catVal + \'\">\' + c" +
                    "atText + \'</option>\';\r\n                            }\r\n                        }\r" +
                    "\n                    }\r\n                    else if (childLastChar == \"2\") {\r\n  " +
                    "                      if (catSplit.length > 6) {\r\n                            va" +
                    "r catVal = \"/\" + catSplit[2] + \"/\" + catSplit[3] + \"/\" + catSplit[4] + \"/\" + cat" +
                    "Split[5];\r\n                            var catText = catSplit[5];\r\n             " +
                    "               catText = catText.replace(\"--\", \" \");\r\n                          " +
                    "  if (allOptions.indexOf(\'<option value=\"\' + catVal + \'\"\') < 0) {\r\n             " +
                    "                   allOptions += \'<option value=\"\' + catVal + \'\">\' + catText + \'" +
                    "</option>\';\r\n                            }\r\n                        }\r\n         " +
                    "           }\r\n                }\r\n            });\r\n\r\n            if (allOptions.l" +
                    "ength > 0) {\r\n                $(\"#\" + childName).append(allOptions);\r\n\r\n        " +
                    "        $(\'#\' + childName).show();\r\n            }\r\n        }\r\n    }\r\n\r\n    // pa" +
                    "ge button click\r\n    function setPagination() {\r\n        $(\'.pagination button[n" +
                    "ame!=0]\').click(function () {\r\n            currentpage = $(this).attr(\'name\');\r\n" +
                    "            setProducts();\r\n        });\r\n    }\r\n\r\n</script>\r\n");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
